import { mkdir, writeFile } from 'node:fs/promises';
import { DARK_TOKENS, LIGHT_TOKENS, THEME_SCHEMA } from '../src/shared/themes';
export const themeArtifacts = {
  'schemas/theme.schema.json': `${JSON.stringify(THEME_SCHEMA, null, 2)}\n`,
  'src/renderer/theme-defaults.css': `/* Generated by bun run generate:themes. */\n:root {\n${Object.entries(DARK_TOKENS).map(([key, value]) => `  --${key}: ${value};`).join('\n')}\n}\n`,
  'skills/dash-bored/references/theme-tokens.md': `# Theme tokens\n\nGenerated from the v1 contract. Both variant maps inherit these defaults. Colors accept six/eight-digit hex; fonts accept local font stacks; radii accept 0–32px; shadows accept none or four integer px lengths and an eight-digit hex color.\n\n| Token | Dark | Light |\n| --- | --- | --- |\n${Object.entries(DARK_TOKENS).map(([key, value]) => `| \`${key}\` | ${value} | ${LIGHT_TOKENS[key as keyof typeof LIGHT_TOKENS]} |`).join('\n')}\n`,
};
if (import.meta.main) {
  await mkdir('schemas', { recursive: true });
  for (const [file, content] of Object.entries(themeArtifacts)) await writeFile(file, content);
}
